name: Integracion Continua FEFO

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener código
      uses: actions/checkout@v3

    - name: Preparar entorno de Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Ejecutar validaciones (Verificar sintaxis)
      run: |
        # flake8 detendrá el proceso si encuentra errores críticos de sintaxis
        flake8 app.py database.py --count --select=E9,F63,F7,F82 --show-source --statistics